@id=1

PUT http://localhost:5077/users/{{id}}
Content-Type: application/json

{
    "username": "zivojindavidovic",
    "email": "zivojindavidovic@gmail.com",
    "password": "zivojindavidovicpassword"
}